# Generated by Django 3.1.6 on 2021-02-07 21:57

from django.db import migrations, models
import gsheets.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210205_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('guid', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=127)),
                ('last_name', models.CharField(max_length=127)),
                ('email', models.CharField(blank=True, default=None, max_length=127, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=127, null=True)),
            ],
            bases=(gsheets.mixins.SheetPushableMixin, models.Model),
        ),
    ]
