# Generated by Django 3.1.6 on 2021-02-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='guid',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
